### ISSUE TITLE
Plenty of warnings while installation

### ISSUE THREAD

**Issue by amrrs** [ropenscilabs/cricketdata#1]
* installing *source* package 'cricinfo' ...
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "1 England"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "2 Australia"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "3 South Africa"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "4 West Indies"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "5 New Zealand"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "6 India"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "7 Pakistan"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "8 Sri Lanka"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "9 Zimbabwe"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning: closing unused connection 6 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=7;team=10;template=results;type=batting;wrappertype=print)
Warning: closing unused connection 5 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=6;team=10;template=results;type=batting;wrappertype=print)
Warning: closing unused connection 4 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=5;team=10;template=results;type=batting;wrappertype=print)
Warning: closing unused connection 3 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=4;team=10;template=results;type=batting;wrappertype=print)
[1] "10 "
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "11 United States of America"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "12 Bermuda"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in .Internal(as.vector(x, mode)) :
  closing unused connection 6 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=7;team=13;template=results;type=batting;wrappertype=print)
Warning in .Internal(as.vector(x, mode)) :
  closing unused connection 5 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=6;team=13;template=results;type=batting;wrappertype=print)
Warning in .Internal(as.vector(x, mode)) :
  closing unused connection 4 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=5;team=13;template=results;type=batting;wrappertype=print)
Warning in .Internal(as.vector(x, mode)) :
  closing unused connection 3 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=4;team=13;template=results;type=batting;wrappertype=print)
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "13 "
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "14 East Africa"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "15 Netherlands"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in .Internal(nchar(x, type, allowNA, keepNA)) :
  closing unused connection 6 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=7;team=16;template=results;type=batting;wrappertype=print)
Warning in .Internal(nchar(x, type, allowNA, keepNA)) :
  closing unused connection 5 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=6;team=16;template=results;type=batting;wrappertype=print)
Warning in .Internal(nchar(x, type, allowNA, keepNA)) :
  closing unused connection 4 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=5;team=16;template=results;type=batting;wrappertype=print)
Warning in .Internal(nchar(x, type, allowNA, keepNA)) :
  closing unused connection 3 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=4;team=16;template=results;type=batting;wrappertype=print)
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "16 "
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "17 Canada"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in standardGeneric("$", .Primitive("$")) :
  closing unused connection 6 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=7;team=18;template=results;type=batting;wrappertype=print)
Warning in standardGeneric("$", .Primitive("$")) :
  closing unused connection 5 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=6;team=18;template=results;type=batting;wrappertype=print)
Warning in standardGeneric("$", .Primitive("$")) :
  closing unused connection 4 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=5;team=18;template=results;type=batting;wrappertype=print)
Warning in standardGeneric("$", .Primitive("$")) :
  closing unused connection 3 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=4;team=18;template=results;type=batting;wrappertype=print)
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "18 "
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "19 Hong Kong"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "20 Papua New Guinea"
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in getClassDef(class1) :
  closing unused connection 6 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=7;team=21;template=results;type=batting;wrappertype=print)
Warning in getClassDef(class1) :
  closing unused connection 5 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=6;team=21;template=results;type=batting;wrappertype=print)
Warning in getClassDef(class1) :
  closing unused connection 4 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=5;team=21;template=results;type=batting;wrappertype=print)
Warning in getClassDef(class1) :
  closing unused connection 3 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=4;team=21;template=results;type=batting;wrappertype=print)
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
[1] "21 "
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning in if (class(raw) != "try-error") countries[i] <- substr(rvest::html_table(raw)[[1]][2,  :
  the condition has length > 1 and only the first element will be used
Warning: closing unused connection 6 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=7;team=22;template=results;type=batting;wrappertype=print)
Warning: closing unused connection 5 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=6;team=22;template=results;type=batting;wrappertype=print)
Warning: closing unused connection 4 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=5;team=22;template=results;type=batting;wrappertype=print)
Warning: closing unused connection 3 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=4;team=22;template=results;type=batting;wrappertype=print)
[1] "22 "
[1] "23 "
[1] "24 "
[1] "25 "
[1] "26 "
[1] "27 "
[1] "28 "
[1] "29 "
[1] "30 "
[1] "31 "
[1] "32 "
[1] "33 "
[1] "34 "
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 127 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=3;team=35;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 126 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;team=35;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 125 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;team=35;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 124 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=10;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 123 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=9;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 122 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=8;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 121 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=7;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 120 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=6;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 119 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=5;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 118 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=4;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 117 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=3;team=34;template=results;type=batting;wrappertype=print)
Warning in structure(list(message = as.character(message), call = call),  :
  closing unused connection 116 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;team=34;template=results;type=batting;wrappertype=print)

**Comment by robjhyndman** [comment]
Try now
