### ISSUE TITLE
Fetching Data not working 

### ISSUE THREAD

**Issue by ald0405** [ropenscilabs/cricketdata#13]
``menODII <- fetch_cricinfo(  "ODI", "Men", "Batting",   type = "innings")
`
```
> `Warning message:                                                                                                          
> closing unused connection 3 (http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;page=219;template=results;type=bowling;view=innings;size=200;wrappertype=print) 
```

**Comment by Sayani07** [comment]
It worked for me and didn't throw any warning. It took 50 minutes since it is extracting a lot of data. So make sure you have a stable internet connection. These messages might occur if an earlier run during the same R session was interrupted.

**Comment by sariya** [comment]
i received the same warning. I'd assume it is due to connection and securities at your organization.
