### ISSUE TITLE
Issue with object 'Wickets'

### ISSUE THREAD

**Issue by ShrinivasIyer** [ropenscilabs/cricketdata#8]
Hi Rob Sir,
Great codes to play with and have fun. Thanks for sharing these. All codes run fine except these 2 below.
I am getting this error. could be a silly one from my side. Thanks for looking into it.

> wt20 %>% 
+     filter(Wickets > 20) %>%
+     ggplot(aes(y = StrikeRate, x = Country)) +
+     geom_boxplot() +
+     geom_point(alpha=0.3, col="blue") +
+     ggtitle("Women T20: Strike Rates") +
+     ylab("Balls per wicket")
Error in filter(., Wickets > 20) : object 'Wickets' not found
In addition: Warning messages:
1: In data.matrix(data) : NAs introduced by coercion
2: In data.matrix(data) : NAs introduced by coercion
3: In data.matrix(data) : NAs introduced by coercion

Also when I run this commands ....fetch_player throws error

> MegLanning <- fetch_player(329336, "ODI")
Error in fetch_player(329336, "ODI") : 
  could not find function "fetch_player"

**Comment by Sayani07** [comment]
Hi,

Try running:

wt20 %>% dplyr::filter(Wickets > 20)  instead of wt20 %>% filter(Wickets > 20).

getAnywhere(filter) gives 2 differing objects matching ‘filter’ which might have created the conflict.

**Comment by ShrinivasIyer** [comment]
> Hi,
> 
> Try running:
> 
> wt20 %>% dplyr::filter(Wickets > 20) instead of wt20 %>% filter(Wickets > 20).
> 
> getAnywhere(filter) gives 2 differing objects matching ‘filter’ which might have created the conflict.

Hi Sayani, This worked. Thanks so much!

**Comment by ShrinivasIyer** [comment]
Also tried this - 

> ViratKohli <- fetch_player_data(253802, "ODI")
> VKohli <- with(ViratKohli, sum(Runs, na.rm=TRUE) / (sum(is.na(Runs)) - sum(dismissals$NotOut)))
Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  object 'dismissals' not found

**Comment by ShrinivasIyer** [comment]
In the second part though I again get this error - 

> VKohli <- with(ViratKohli, sum(Runs, na.rm=TRUE) / (sum(is.na(Runs)) - sum(Dismissals=="NotOut")))
Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  object 'Dismissals' not found

**Comment by Sayani07** [comment]
Try this out: 

```{r, echo=FALSE}
VKohli <- with(ViratKohli, sum(Runs, na.rm=TRUE) / (sum(!is.na(Runs)) - sum(if_else(Dismissal=="not out",1,0),na.rm=TRUE)))
names(VKohli) <- paste("Average =", round(VKohli,2))
ViratKohli %>% filter(Dismissal== "not out") %>% ggplot() +
 geom_point(aes(x = Start_Date, y = Runs, col = Dismissal)) +
ggtitle("Virat Kohli ODI Scores") +
geom_hline(aes(yintercept=VKohli)) +
scale_y_continuous(sec.axis = sec_axis(~ ., breaks=VKohli))
```

**Comment by ShrinivasIyer** [comment]
Thanks but getting error again -



> VKohli <- with(ViratKohli, sum(Runs, na.rm=TRUE) / (sum(!is.na(Runs)) -
sum(if_else(Dismissal=="not out",1,0),na.rm=TRUE)))
Error in if_else(Dismissal == "not out", 1, 0) :
  could not find function "if_else"
> names(VKohli) <- paste("Average =", round(VKohli,2))
Error in paste("Average =", round(VKohli, 2)) : object 'VKohli' not found
> ViratKohli %>% filter(Dismissal== "not out") %>% ggplot() +
+     geom_point(aes(x = Start_Date, y = Runs, col = Dismissal)) +
+     ggtitle("Virat Kohli ODI Scores") +
+     geom_hline(aes(yintercept=VKohli)) +
+     scale_y_continuous(sec.axis = sec_axis(~ ., breaks=VKohli))
Error in filter(., Dismissal == "not out") : object 'Dismissal' not found
In addition: Warning messages:
1: In data.matrix(data) : NAs introduced by coercion
2: In data.matrix(data) : NAs introduced by coercion
3: In data.matrix(data) : NAs introduced by coercion


*Shrinivas Iyer*

*linkedin.com/in/shrinivasiyer <http://linkedin.com/in/shrinivasiyer>*

+91 9515673173

**Comment by lukewratten** [comment]
Hi,

I would imagine the if_else function is part of a package that you don't have loaded. ifelse() is the base function in R.

Have you used the cricketdata package to download data into the ViratKohli tibble?

Regards

**Comment by ShrinivasIyer** [comment]
Hello,

Yes i have loaded cricketdata library and also tibble VoratKohli is
download.
Thanks

**Comment by Sayani07** [comment]
Hi,

The if_else function is a part of the package dplyr, which is not loaded.

> VKohli <- with(ViratKohli, sum(Runs, na.rm=TRUE) / (sum(!is.na(Runs)) -
> sum(if_else(Dismissal=="not out",1,0),na.rm=TRUE))) Error in if_else(Dismissal == "not out", 1, 0) : could not find function "if_else"

Please load the package dplyr (or tidyverse) before running the examples. The package provides the data in tibbles. If you want to play with it,  you need to load packages which are specific to your analysis.

**Comment by ShrinivasIyer** [comment]
Okay sure I will load dplyr. Thanks for the correction.

**Comment by Sayani07** [comment]
No worries. I believe it worked now. 

Thanks
